name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # vagy 'master', attól függően, melyik a főágad
    paths:
      - Dockerfile
      - '**/*.py'
      - .github/workflows/docker-publish.yml
      - requirements.txt

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: varhegyisz/jsbonbin-server:latest